spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/master/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://USERSERVICE
              predicates:
                - Path=/api/users/**
            - id: aiservice
              uri: lb://AISERVICE
              predicates:
                - Path=/api/recommendations/**
            - id: activityservice
              uri: lb://ACTIVITYSERVICE
              predicates:
                - Path=/api/activities/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
